### ISSUE TITLE
Can't get message on channel, but worker thread is running

### ISSUE THREAD

**Issue by unnatic312** [edigiacomo/asgi-mqtt#3]
I found in console.................

Starting Channels development server at http://127.0.0.1:8000/
Channel layer default (asgi_redis.core.RedisChannelLayer)
Quit the server with CTRL-BREAK.
2017-11-10 16:30:49,223 - INFO - worker - Listening on channels http.request, mqttsub, websocket.connect, websocket.disconnect, websocket.receive
2017-11-10 16:30:49,223 - INFO - worker - Listening on channels http.request, mqttsub, websocket.connect, websocket.disconnect, websocket.receive
2017-11-10 16:30:49,223 - INFO - worker - Listening on channels http.request, mqttsub, websocket.connect, websocket.disconnect, websocket.receive
2017-11-10 16:30:49,223 - INFO - server - HTTP/2 support enabled
2017-11-10 16:30:49,223 - INFO - server - Using busy-loop synchronous mode on channel layer
2017-11-10 16:30:49,223 - INFO - server - Listening on endpoint tcp:port=8000:interface=127.0.0.1

when I publish message to topic mqttsub, it doesn't received to this end.

please help me through this.

**Comment by edigiacomo** [comment]
The channel name is `mqtt.sub` (you've missed the dot).

**Comment by unnatic312** [comment]
As you explain in usage guidlines...

Connect the server to a running MQTT broker:
**asgimqtt --host localhost --port 1883 django_project.asgi:channel_layer**

_I write this command line in windows PowerShell,But it seems unrecognized and rise error._
 I am unable to connect my channel to mqtt broker.


How I will connect my channel to mqtt broker???

**Comment by edigiacomo** [comment]
> I write this command line in windows PowerShell,But it seems unrecognized and rise error.

What kind of error? Can you dump the stacktrace?

> 2017-11-10 16:30:49,223 - INFO - worker - Listening on channels http.request, mqttsub, websocket.connect, websocket.disconnect, websocket.receive

My previous suggestion is still valid: you should find `mqtt.sub` in the channels list, not `mqttsub`.

**Comment by unnatic312** [comment]
After making mqtt.sub still not receiving any message.

setting.py  
**CHANNEL_LAYERS = {
    'default': {
         "BACKEND": "asgi_redis.RedisChannelLayer",
        'CONFIG': {
            'hosts': [('127.0.0.1',6379)],
        },
        "ROUTING": 'final_1.routing.channel_routing',
    }
}**

routing.py

**channel_routing = [
    route('mqtt.sub', on_mqtt_message),
]**

**Comment by edigiacomo** [comment]
> After making mqtt.sub still not receiving any message.

Ok, I think we have solved one of the two problems you have.

> I write this command line in windows PowerShell,But it seems unrecognized and rise error.

I think you still have the error in the command, right? I ask you again for the stacktrace of the error.

**Comment by unnatic312** [comment]
C:\Users\Jimmy\Desktop\final_1>asgimqtt --host localhost --port 1883 django_project.asgi:channel_layer
'asgimqtt' is not recognized as an internal or external command,
operable program or batch file.

**Comment by edigiacomo** [comment]
You have to install the package e.g. in a virtualenv.

I haven't published the package in pypi, so `pip install` is not an option and you have to build the package.

[Activate your virtualenv](https://virtualenv.pypa.io/en/stable/userguide/#activate-script), then:

1. Create the `asgimqtt` package: `python setup.py sdist`
2. Install the package inside virtualenv `pip install dist/asgimqtt-0.1.tar.gz`
3. Run the command

**Comment by unnatic312** [comment]
thank you Sir...

**Comment by edigiacomo** [comment]
I have uploaded the package to pypi and added an example project (see `examples/example_project`) with some documentation.

I close the issue, feel free to reopen it if your problems persist.
