### ISSUE TITLE
MQTT- django-channels

### ISSUE THREAD

**Issue by sabuhish** [edigiacomo/asgi-mqtt#5]
Hello, does this package supports django channels 2.0 above?We have devices publishing mesages to broker and django subscribing all this topics. We need to pass data to webscokets as real-time. DO you think it is useful to use as real-time data to front?

**Comment by edigiacomo** [comment]
> Hello, does this package supports django channels 2.0 above?

I'm sorry, this package doesn't support channels 2 (see issue #4).

> We have devices publishing mesages to broker and django subscribing all this topics. We need to pass data to webscokets as real-time. DO you think it is useful to use as real-time data to front?

Yes, see the example project https://github.com/edigiacomo/asgi-mqtt/tree/master/examples/example_project (but you have to install channels < 2.0).
